[general]
import = [
    "~/.config/alacritty/monokai_pro.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 9

[window]
padding.x = 4
padding.y = 4
dimensions = { columns = 180, lines = 40 }
